#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --partition=a100
#SBATCH --job-name=predict_hipmri
#SBATCH -o predict_%j.out
#SBATCH --time=01:00:00

# Initialize conda
source ~/miniconda3/etc/profile.d/conda.sh
conda activate torch

python train.py
python predict.py

